title: "Harvey Ge’s Playground"
author: "harveyge"
description: "Harvey Ge’s playground and showcase"
permalink: /:slug/               # use the page/post slug (no spaces/apostrophes)
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Theme
remote_theme: "chesterhow/jekyll-contrast"  # or your fork

# Layout options
show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Main navigation
navigation:
  - { title: "Home",    url: "/",               icon: "home" }
  - { title: "About Me", url: "/about/",        icon: "address-card" }
  - { title: "Resume",  url: "/assets/HaifengGeCV.pdf", icon: "file-pdf" }

# Footer / social links
external:
  - { title: "Mail",      icon: "envelope",    url: "mailto:harveygeus@gmail.com" }
  - { title: "GitHub",    icon: "github",      url: "https://github.com/harveyge" }
  - { title: "Instagram", icon: "instagram",   url: "https://www.instagram.com/shs_eagles/" }

# Comments (uncomment and configure if you enable)
# comments:
#   disqus_shortname: "YOUR_SHORTNAME"
#   isso_domain: "your-isso-domain.org"

plugins:
  - jekyll-feed
